openapi: 3.0.0
info:
  title: Logistics Tracker API
  version: 1.0.0
paths:
  /api/register:
    post:
      summary: Register user
  /api/login:
    post:
      summary: Login user
  /api/shipments:
    post:
      summary: Create new shipment
  /api/shipments/{shipment_id}:
    get:
      summary: Get shipment by ID
  /api/shipments/{shipment_id}/status:
    put:
      summary: Update shipment status
